LESSON_SEED_DATA = [
    # Month 1 — Kompyuter Asoslari + Typing + Google Account + Office
    {"month": 1, "week": 1, "lesson_number": 1, "title": "Kompyuter nima? Qismlar va ularning vazifalari"},
    {"month": 1, "week": 1, "lesson_number": 2, "title": "Operatsion tizim — Windows asoslari"},
    {"month": 1, "week": 1, "lesson_number": 3, "title": "Fayl tizimi — papka, fayl, kengaytma"},
    {"month": 1, "week": 2, "lesson_number": 4, "title": "Typing asoslari — barmoq qo'yish texnikasi (10 barmoq)"},
    {"month": 1, "week": 2, "lesson_number": 5, "title": "Typing mashqi — tezlik va aniqlikni oshirish"},
    {"month": 1, "week": 2, "lesson_number": 6, "title": "Google Account ochish, Gmail, Google Drive bilan tanishish"},
    {"month": 1, "week": 3, "lesson_number": 7, "title": "Word interfeysini o'rganish, matn terish"},
    {"month": 1, "week": 3, "lesson_number": 8, "title": "Formatlash — shrift, rang, hizalash"},
    {"month": 1, "week": 3, "lesson_number": 9, "title": "Jadval va rasmlar qo'shish"},
    {"month": 1, "week": 4, "lesson_number": 10, "title": "Excel interfeysini o'rganish, ma'lumot kiritish"},
    {"month": 1, "week": 4, "lesson_number": 11, "title": "Formulalar — SUM, AVERAGE, COUNT"},
    {"month": 1, "week": 4, "lesson_number": 12, "title": "Grafik va diagrammalar"},
    # Month 2 — Google Xizmatlar + Scratch + Canva
    {"month": 2, "week": 5, "lesson_number": 13, "title": "Google Docs — matn yaratish va ulashish"},
    {"month": 2, "week": 5, "lesson_number": 14, "title": "Google Sheets — jadval va formulalar"},
    {"month": 2, "week": 5, "lesson_number": 15, "title": "Google Slides — prezentatsiya yaratish"},
    {"month": 2, "week": 6, "lesson_number": 16, "title": "Prezentatsiya yaratish asoslari (PowerPoint)"},
    {"month": 2, "week": 6, "lesson_number": 17, "title": "Animatsiya va dizayn qo'shish"},
    {"month": 2, "week": 6, "lesson_number": 18, "title": "Amaliy loyiha — o'zi haqida prezentatsiya"},
    {"month": 2, "week": 7, "lesson_number": 19, "title": "Scratch nima? Interfeys, Sprite va fon"},
    {"month": 2, "week": 7, "lesson_number": 20, "title": "Harakat, takrorlash (loop), shartlar (if/else)"},
    {"month": 2, "week": 7, "lesson_number": 21, "title": "Amaliy loyiha — oddiy o'yin yaratish"},
    {"month": 2, "week": 8, "lesson_number": 22, "title": "Canva interfeysini o'rganish"},
    {"month": 2, "week": 8, "lesson_number": 23, "title": "Poster va banner yaratish"},
    {"month": 2, "week": 8, "lesson_number": 24, "title": "Amaliy loyiha — voqea uchun afisha"},
    # Month 3 — Figma + AI Vositalar + Yakuniy Loyiha
    {"month": 3, "week": 9, "lesson_number": 25, "title": "Figma nima? Interfeys bilan tanishish"},
    {"month": 3, "week": 9, "lesson_number": 26, "title": "Shakllar, ranglar, matn bilan ishlash"},
    {"month": 3, "week": 9, "lesson_number": 27, "title": "Amaliy loyiha — oddiy veb-sahifa dizayni"},
    {"month": 3, "week": 10, "lesson_number": 28, "title": "Internet xavfsizligi, parol himoyasi"},
    {"month": 3, "week": 10, "lesson_number": 29, "title": "AI nima? ChatGPT bilan tanishish va ishlatish"},
    {"month": 3, "week": 10, "lesson_number": 30, "title": "Gemini, Copilot — farqlari va qo'llanilishi"},
    {"month": 3, "week": 11, "lesson_number": 31, "title": "AI bilan matn yozish va tahrirlash"},
    {"month": 3, "week": 11, "lesson_number": 32, "title": "AI bilan rasm yaratish (Canva AI, Gemini)"},
    {"month": 3, "week": 11, "lesson_number": 33, "title": "AI vositalaridan to'g'ri foydalanish — etika"},
    {"month": 3, "week": 12, "lesson_number": 34, "title": "Yakuniy loyihani tayyorlash"},
    {"month": 3, "week": 12, "lesson_number": 35, "title": "Loyihani taqdim etish (prezentatsiya)"},
    {"month": 3, "week": 12, "lesson_number": 36, "title": "Sertifikat topshirish + kurs xulosasi"},
]

